# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool: Default

steps:
- task: Npm@1
  inputs:
    command: 'install'
- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'run build'
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/build/'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(System.ArtifactStagingDirectory)/drop.zip'
    replaceExistingArchive: true
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Visual Studio Enterprise Subscription – MPN (1a205f89-f0b2-4f0e-aca0-89ef95ae54e2)'
    appType: 'webApp'
    WebAppName: 'slots-zivi'
    packageForLinux: '$(System.ArtifactStagingDirectory)/drop.zip'
